### ISSUE TITLE
There is no "destroy" event

### ISSUE THREAD

**Issue by tuanjihoo** [milkamil93/mobile-swipe-menu#1]
Please add "destroy" event

**Comment by kamilsmtv** [comment]
> Please add "destroy" event

Event or method? Describe your task.

**Comment by ABC-template** [comment]
Наверное имеется ввиду метод, так же, как я понимаю отсутствует метод 'disable'. То есть игнорирования скрипта на определенном участке страницы, например блок расположения слайдера, и подобные элементы с скроллом. Спасибо.

**Comment by kamilsmtv** [comment]
> Наверное имеется ввиду событие, так же как я понимаю отсутствует событие 'disable'. То есть игнорирования скрипта на определенном участке страницы, например блок расположения слайдера, и подобные элементы с скроллом. Спасибо.

Такая возможность имеется, позднее реализую как полноценный метод, но сейчас можно сделать так

```
var menu = new MobileSwipeMenu('#menu', {
    mode: 'right',
    width: window.innerWidth / 1.15
});
menu.lock = true;
```

**Comment by ABC-template** [comment]
> > Наверное имеется ввиду событие, так же как я понимаю отсутствует событие 'disable'. То есть игнорирования скрипта на определенном участке страницы, например блок расположения слайдера, и подобные элементы с скроллом. Спасибо.
> 
> Такая возможность имеется, позднее реализую как полноценный метод, но сейчас можно сделать так
> 
> ```
> var menu = new MobileSwipeMenu('#menu', {
>     mode: 'right',
>     width: window.innerWidth / 1.15
> });
> menu.lock = true;
> ```

Хорошо, ждём. Большое спасибо!

**Comment by kamilsmtv** [comment]
В релизе [2.1.0](https://github.com/milkamil93/mobile-swipe-menu/commit/957af92cc44431555045e81fe6f83778cc1cd583) добавлены методы `disableSwipe` и `enableSwipe`
