### ISSUE TITLE
Weird behavior after resize

### ISSUE THREAD

**Issue by jirisykora83** [milkamil93/mobile-swipe-menu#2]
Hi thanks for nice library,

i facing issue when try to use library on mobile when device is flip (and it fore to change windows size). This Can be simulate even with chrome dev tool.

![image](https://user-images.githubusercontent.com/7279825/127626807-b95186d0-504b-4a0d-9cbd-f444fc641f60.png)

![image](https://user-images.githubusercontent.com/7279825/127626850-c46d682e-dbeb-404b-ac8c-aa8c2a70bcdf.png)

**Comment by kamilsmtv** [comment]
You need to track the [flip](https://developer.mozilla.org/ru/docs/Web/API/CSS_Object_Model/Managing_screen_orientation) of the screen and override the width with the 'setWidth' method. This was added in version 2.1.2, so you should update.

Example:
```
import MobileSwipeMenu from 'mobile-swipe-menu'
const portraitWidth = 300
const menu = new MobileSwipeMenu('#menu', {
    mode: 'right',
    width: portraitWidth
})
screen.addEventListener('orientationchange', () => {
    switch(window.orientation) {  
        case -90 || 90: // landscape
            menu.setWidth(600)
        break; 
        default: // portrait
            menu.setWidth(portraitWidth)
        break; 
    }
})
```

**Comment by kamilsmtv** [comment]
Sorry, you need version [2.2.0](https://github.com/milkamil93/mobile-swipe-menu/releases/tag/2.2.0)

**Comment by jirisykora83** [comment]
Thanks for fast fix 👍
