### ISSUE TITLE
Closing menu is laggy on iOS Safari browser

### ISSUE THREAD

**Issue by marcinkardas** [milkamil93/mobile-swipe-menu#5]
Hey Kamil, 

I am trying to use your mobile menu but I saw there is problem with menu on Safari. When I am trying to close menu (by swiping) it is closing but it is so laggy. Everything is fine on Firefox, Chrome. Do you know what is the problem? If you don't have possibility to test this on iOS, I can help you. Maybe this video will help you:

https://user-images.githubusercontent.com/25573757/159086894-e2a3ecb6-a8bd-46a3-b8a8-0fb8bfe2a9a7.mov

**Comment by kamilsmtv** [comment]
@marcinkardas Hi. Checked on iphone 12 in Safari, I did not notice any problem.
